name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - name: Build
        run: cargo build --verbose --release
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          body_path: ${{ github.workspace }}\CHANGELOG.md
          files: ${{ github.workspace }}\target\release\mx_replay_uploader.exe